name: Coding standards

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'
  pull_request: ~

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://oskarstark/php-cs-fixer-ga:3.26.0
        with:
          args: --diff --dry-run
